### ISSUE TITLE
Having trouble finding a file

### ISSUE THREAD

**Issue by weisisheng** [FilipPyrek/aws-cloudday-2023-trpc#1]
Oddly, in packages/frontend/src/utils/trpc.ts, the first line ,"import type { AppRouter } from '@core/trpc/router' ", gives me an error "can not find module".

Even when I fix the path to where the file is found, "@core/src/trpc/router", the error remains.  Clearly the AppRouter is being exported.  Restarted VS Code and the TS server, no luck.

I am a relative noob at TS so would appreciate any hints, tips, tricks.  TIA.

**Comment by FilipPyrek** [comment]
Hi, sorry, I will answer any more comments after I give my presentation on AWS CloudDay Prague. If you want, we can chat there. 🙂

**Comment by weisisheng** [comment]
OK. best of luck.
